### ISSUE TITLE
Implement and benchmark LazyItemVec for inverted index

### ISSUE THREAD

**Issue by tinkn** [cosdata/cosdata#106]
* TODO Integrate and benchmark LazyItemVec for inverted index
:PROPERTIES:
:CREATED: [2024-09-17 Tue]
:END:

** Description
Reuse the LazyItemVec and perform benchmarks against alternative implementations to assess its performance and efficiency.

** Tasks
- [ ] Review the already implemented LazyItemVec
- [ ] Design benchmark tests
- [ ] Run benchmarks against alternative implementations
- [ ] Analyze and document results

** Priority
High

** Labels
enhancement, performance

**Comment by truthixify** [comment]
Can I jump on this?
