### ISSUE TITLE
Implement versioning for Inverted Index

### ISSUE THREAD

**Issue by tinkn** [cosdata/cosdata#108]
* TODO Implement versioning for Inverted Index
:PROPERTIES:
:CREATED: [2024-09-17 Tue]
:END:

** Description
Implement versioning for the Inverted Index, similar to the current implementation for dense vector HNSW index using LazyItemVec.

** Tasks
- [ ] Review current versioning implementation for HNSW index
- [ ] Design versioning approach for Inverted Index
- [ ] Implement versioning
- [ ] Test and validate versioning functionality

** Priority
Medium

** Labels
enhancement
