### ISSUE TITLE
Implement kNN query for Inverted Index

### ISSUE THREAD

**Issue by tinkn** [cosdata/cosdata#109]
* TODO Implement kNN query for Inverted Index
:PROPERTIES:
:CREATED: [2024-09-17 Tue]
:END:

** Description
Implement the query to find the kNN top matches in the Inverted Index. Review the design document for implementation details and explore potential improvements or optimizations.

** Tasks
- [ ] Review design document for implementation details
- [ ] Implement kNN query functionality
- [ ] Explore and implement optimizations or improved heuristics
- [ ] Benchmark and validate the implementation

** Priority
High

** Labels
enhancement, performance
