### ISSUE TITLE
Implement API for vector retrieval from index

### ISSUE THREAD

**Issue by tinkn** [cosdata/cosdata#110]
* TODO Implement API for raw sparse vector retrieval from index
:PROPERTIES:
:CREATED: [2024-09-17 Tue]
:END:

** Description
Create an API to retrieve a raw vector from the LMDB index and raw file. This should work for sparse vectors, as it does currently for the dense vectors, utilizing a raw file storage approach.

** Tasks
- [ ] Design API for vector retrieval
- [ ] Implement raw vector retrieval for sparse vectors
- [ ] Integrate with raw file storage system
- [ ] Test and validate retrieval functionality

** Priority
High

** Labels
enhancement, api
